In [710]:
import numpy as np
import matplotlib.pyplot as plt
# 一维数组
a = np.array([6,2,3,4,5,7,8,9])
a1 = np.array([9875,75,76543,5,0,4])
print(a)

[6 2 3 4 5 7 8 9]


In [711]:
# 二维数组
b = np.array([[1, 2, 3], [3, 4, 5]])
print(b)

[[1 2 3]
 [3 4 5]]


In [712]:
#获取数组维度
D = np.ndim(b)
print(D)

2


In [713]:
# 访问指定元素
Check = np.where(b == 1)
print(Check)

(array([0], dtype=int64), array([0], dtype=int64))


In [714]:
# 修改特定元素
a[0] = 6
print(a)

[6 2 3 4 5 7 8 9]


In [715]:
# 切片获取子集
print(a[0:6])

[6 2 3 4 5 7]


In [716]:
# 复制数组
c = a
print(c)

[6 2 3 4 5 7 8 9]


In [717]:
# 合并
Add = np.append(a, a1)
print(Add)

[    6     2     3     4     5     7     8     9  9875    75 76543     5
     0     4]


In [718]:
# 分割数组为多个子集
Split = np.split(a, 4)
for i in range(4):
    print(Split[i])

[6 2]
[3 4]
[5 7]
[8 9]


In [719]:
# 搜索特定元素
Sreach = np.where( a == 3)
print(Sreach)

(array([2], dtype=int64),)


In [720]:
# 数组排序
Order = np.sort(a1)
print(Order)

[    0     4     5    75  9875 76543]


In [721]:
# 13.过滤
Filter = Order[Order > 5]
print(Filter)

[   75  9875 76543]


In [722]:
# 数据类型

In [723]:
# 如何指定数据类型
c = np.array([1, 2, 8, 9, 6, 5, 87, 23], dtype=int)
print(c)

[ 1  2  8  9  6  5 87 23]


In [724]:
# 转换数组数据类型
f = c.astype(float)
print(f)

[ 1.  2.  8.  9.  6.  5. 87. 23.]


In [725]:
# 比较两个数组数据类型是否相等
if(c.dtype == f.dtype):
    print("Type of c is same as Type of f!")
else:
    print("No!")

No!


In [726]:
# 数组形状

In [727]:
# 获取数组形状
Shape = np.shape(b)
print(Shape)

(2, 3)


In [728]:
# 改变形状
print(a)
A_resh = np.reshape(a, (1, 8))
print(A_resh)

[6 2 3 4 5 7 8 9]
[[6 2 3 4 5 7 8 9]]


In [729]:
# 如何迭代访问数组元素
col, row = np.shape(b)
print(col, row)
for i in range(col):
    for j in range(row):
        print(b[i][j] ,end =" ")

2 3
1 2 3 3 4 5 

In [730]:
# 数学运算

In [731]:
# 加减乘除
AddArray = np.add(a, c)#形状一样的相加
print(AddArray)
SubArray = np.subtract(a, c)
print(SubArray)
MulArray = np.multiply(a, c)
print(MulArray)
DivArray = np.divide(a, c)
print(DivArray)

[ 7  4 11 13 11 12 95 32]
[  5   0  -5  -5  -1   2 -79 -14]
[  6   4  24  36  30  35 696 207]
[6.         1.         0.375      0.44444444 0.83333333 1.4
 0.09195402 0.39130435]


In [732]:
# 四舍五入
Around = np.around(DivArray)
print(Around)
# 对数运算
LogArray = np.log(a)
print(LogArray)

[6. 1. 0. 0. 1. 1. 0. 0.]
[1.79175947 0.69314718 1.09861229 1.38629436 1.60943791 1.94591015
 2.07944154 2.19722458]


In [733]:
# 数组的和 积 差
Sum = np.sum(a)
print(Sum)

Prod = np.prod(a)
print(Prod)

aN = -a
SumN = np.sum(aN)
print(SumN)

44
362880
-44


In [734]:
# 最小公倍数 最大公约数
Least = np.gcd(a, c)
print(Least)
Largest = np.lcm(a,c)
print(Largest)

[1 2 1 1 1 1 1 1]
[  6   2  24  36  30  35 696 207]


In [735]:
# 三角 双曲
SinArray = np.sin(a)
CosArray = np.cos(a)
TanArray = np.tan(a)
SinhArray = np.sinh(a)
CoshArray = np.cosh(a)
TanhArray = np.tanh(a)
print(SinArray)
print(CosArray)
print(TanArray)
print(SinhArray)
print(CoshArray)
print(TanhArray)


[-0.2794155   0.90929743  0.14112001 -0.7568025  -0.95892427  0.6569866
  0.98935825  0.41211849]
[ 0.96017029 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.75390225
 -0.14550003 -0.91113026]
[-0.29100619 -2.18503986 -0.14254654  1.15782128 -3.38051501  0.87144798
 -6.79971146 -0.45231566]
[2.01713157e+02 3.62686041e+00 1.00178749e+01 2.72899172e+01
 7.42032106e+01 5.48316123e+02 1.49047883e+03 4.05154190e+03]
[2.01715636e+02 3.76219569e+00 1.00676620e+01 2.73082328e+01
 7.42099485e+01 5.48317035e+02 1.49047916e+03 4.05154203e+03]
[0.99998771 0.96402758 0.99505475 0.9993293  0.9999092  0.99999834
 0.99999977 0.99999997]


In [736]:
# 集合交并差补
Intersect = np.intersect1d(a, c)
Union = np.union1d(a, c)
Diff = np.setdiff1d(a, c)
Or = np.setxor1d(a, c)


In [737]:
# 线代

In [738]:
# 矩阵乘法 转置 逆 求行列式 特征值 特征向量
Mat = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

Mat2 = np.array([[0.1, 2, 3.1],[4.2, 5.1, 6.23],[7.4, 8.9, 9.354]])
print(np.dot(Mat, Mat2))
print(Mat.T)
print(np.linalg.inv(Mat2))

print(np.linalg.det(Mat))
# 特征值 特征向量
print(np.linalg.eig(Mat))

[[ 30.7    38.9    43.622]
 [ 65.8    86.9    99.674]
 [100.9   134.9   155.726]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[-0.6594073   0.75654331 -0.2853434 ]
 [ 0.58049921 -1.87428877  1.05594093]
 [-0.03066377  1.18481394 -0.67204759]]
0.0
(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [739]:
# 随机模块

In [740]:
# 随机整数
RanInt = np.random.randint(1000)
print(RanInt)
# 随机浮点
RanFloat = np.random.uniform(0, 10)
print(RanFloat)
# 一定范围的整数
RanRge = np.random.randint(1, 9999)
# Normal
N = np.random.normal(0, 1, size=5)
print(N)
# Bin
Bin = np.random.binomial(50,0.5, size=5)
print(Bin)
# Poisson
Poisson = np.random.poisson(10, size=5)
print(Poisson)

425
7.091475537578019
[-0.19856296 -1.37149865 -1.12480871 -1.18373692 -0.74569594]
[24 27 27 23 27]
[10 15 15 11 12]
